,"clickEvent":{"action":"suggest_command","value":"/trigger withdraw set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to withdraw","color":"white"},{"text":"\nfrom wallet","color":"gray"}]}
,"clickEvent":{"action":"suggest_command","value":"/trigger withdraw set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to withdraw","color":"white"},{"text":"\nfrom wallet","color":"gray"}]}}
,"clickEvent":{"action":"suggest_command","value":"/trigger withdraw set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to withdraw","color":"white"},{"text":"\nfrom wallet","color":"gray"}]}}
,"clickEvent":{"action":"suggest_command","value":"/trigger withdraw set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to withdraw","color":"white"},{"text":"\nfrom wallet","color":"gray"}]}}
,"clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}
,"clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}


tellraw @s[scores={nuggets=1..}] ["",{"text":"[ ✎ ]","color":"gray","clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"},{"text":"\nAccepts: whole numbers 0+","color":"dark_gray"}]}},{"text":" Pay ","color":"gold","clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"}]}},{"selector":"@a[tag=pay.target,limit=1]","color":"yellow"},{"text":" - ","color":"gold"},{"text":"(Balance: ","color":"green","clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}},{"text":"$","color":"red","clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}},{"score":{"name":"@s","objective":"nuggets"},"color":"red","clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}},{"text":" - Wallet: ","color":"green","clickEvent":{"action":"suggest_command","value":"/trigger withdraw set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to withdraw","color":"white"},{"text":"\nfrom wallet","color":"gray"}]}},{"text":"$","color":"red"},{"score":{"name":"@s","objective":"nugget.wallet"},"color":"red"},{"text":")","color":"green"}]


tellraw @s[scores={nuggets=1..}] ["",{"text":"[ ✎ ]","color":"gray","clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"},{"text":"\nAccepts: whole numbers 0+","color":"dark_gray"}]}},{"text":" Pay ","color":"gold","clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"}]}},{"selector":"@a[tag=pay.target,limit=1]","color":"yellow","clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"}]}},{"text":" - ","color":"gold"},{"text":"(Balance: ","color":"green","clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}},{"text":"$","color":"red","clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}},{"score":{"name":"@s","objective":"nuggets"},"color":"red","clickEvent":{"action":"suggest_command","value":"/trigger deposit set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to deposit","color":"white"},{"text":"\nto wallet","color":"gray"}]}},{"text":" - Wallet: ","color":"green","clickEvent":{"action":"suggest_command","value":"/trigger withdraw set "},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to withdraw","color":"white"},{"text":"\nfrom wallet","color":"gray"}]}},{"text":"$","color":"red"},{"score":{"name":"@s","objective":"nugget.wallet"},"color":"red"},{"text":")","color":"green"}]
,"clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"}]}
,{"text":" Pay ","color":"gold","clickEvent":{"action":"suggest_command","value":"/trigger paysend set "},"hoverEvent":{"action":"show_text","contents":["",{"text":"Click to enter amount to pay player.","color":"gray"}]}